# Generated by Django 2.2.1 on 2019-05-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190522_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='hours',
        ),
    ]
