# Generated by Django 2.2.1 on 2019-05-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_interview_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='slot_days',
            field=models.IntegerField(default=20),
        ),
    ]
