# Generated by Django 2.2.1 on 2019-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interview_slot_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='start_date',
        ),
        migrations.AddField(
            model_name='interview',
            name='end_hour',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='interview',
            name='start_hour',
            field=models.IntegerField(default=9),
        ),
    ]
